import flet as ft
from database.members import Member
from database.models import ModelMember
import time
def restriction(e):
    num_char=len(e.control.value)
    max=e.control.max_length
    e.control.helper_text=f'{num_char}/{max}'

class text_edit(ft.TextField):
    def __init__(self,label,value,icon,length,filter_by):
        super().__init__()
        self.label=label
        self.value=value
        self.content_padding=ft.padding.only(bottom=10, right=3)
        self.width=260
        self.height=74
        self.label_style=ft.TextStyle(color=ft.colors.LIGHT_BLUE_900,weight=ft.FontWeight.BOLD)
        self.color=ft.colors.ORANGE_ACCENT_700
        self.prefix_icon=icon
        self.border_color=ft.colors.ORANGE_ACCENT_700
        self.max_length=length
        self.helper_text=""
        self.helper_style=ft.TextStyle(color=ft.colors.ORANGE_ACCENT_700)
        self.input_filter=filter_by
        self.on_change=restriction

class text_create(ft.TextField):
    def __init__(self,label,value,icon,length,filter_by):
        super().__init__()
        self.label=label
        self.value=value
        self.content_padding=ft.padding.only(bottom=10, right=3)
        self.width=278
        self.height=74
        self.label_style=ft.TextStyle(color=ft.colors.ORANGE_ACCENT_700,weight=ft.FontWeight.BOLD)
        self.color=ft.colors.LIGHT_BLUE_900
        self.prefix_icon=icon
        self.border_color=ft.colors.LIGHT_BLUE_900
        self.max_length=length
        self.helper_text=""
        self.helper_style=ft.TextStyle(color=ft.colors.LIGHT_BLUE_900)
        self.input_filter=filter_by
        self.on_change=restriction

def panel(page,search,add):
    #lista total
    Member_list= ModelMember.dashboard()
    #guardar objetos en variables para editar
    nacionalidad=text_edit(" Nacionalidad","",ft.icons.PERM_IDENTITY,15,ft.TextOnlyInputFilter())
    cedula=text_edit(" Cédula","",ft.icons.PERM_IDENTITY,10,ft.NumbersOnlyInputFilter())
    situacion=text_edit(" Situación","",ft.icons.LOCATION_HISTORY_SHARP,400,None)
    nombre=text_edit(" Nombre Completo","",ft.icons.PERM_IDENTITY,55,ft.TextOnlyInputFilter())
    edad=text_edit(" Edad","",ft.icons.ACCESS_TIME_OUTLINED,2,ft.NumbersOnlyInputFilter())
    ocupacion=text_edit(" Ocupación","",ft.icons.WORK,55,None)
    lugar=text_edit(" Lugar de ocupación","",ft.icons.PLACE_ROUNDED,40,None)
    estudios=text_edit(" Estudios","",ft.icons.HISTORY_EDU_SHARP,30,None)
    cargo=text_edit("Cargos","",ft.icons.WORKSPACE_PREMIUM,25,ft.TextOnlyInputFilter())
    responsabilidad=text_edit(" Responsabilidad en la Iglesia","",ft.icons.FACT_CHECK_SHARP,35,None)
    vehiculo=text_edit(" Vehículo","",ft.icons.DIRECTIONS_CAR,20,ft.TextOnlyInputFilter())
    estado_civil=text_edit(" Estado Civil","",ft.icons.FAMILY_RESTROOM_ROUNDED,15,ft.TextOnlyInputFilter())
    hijos=text_edit(" Cantidad de Hijos","",ft.icons.CHILD_FRIENDLY_OUTLINED,1,ft.NumbersOnlyInputFilter())
    telefono=text_edit(" Teléfono","",ft.icons.PHONE_ROUNDED,15,ft.NumbersOnlyInputFilter())
    #guardar oobjetos en variables para crear registros
    #abrir cerrar y enviar informacion a los dialog
    def edit(e,member):
        nacionalidad.value=member.nationality
        cedula.value=member.DNI
        nombre.value=member.full_name
        edad.value=member.age
        ocupacion.value=member.occupation
        lugar.value=member.occupation_place
        estudios.value=member.knowledge
        cargo.value=member.hierarchy
        responsabilidad.value=member.responsabilities
        vehiculo.value=member.vehicle
        estado_civil.value=member.civil_status
        hijos.value=member.childrens
        telefono.value=member.phone
        situacion.value=member.situation
        situacion.multiline=True
        situacion.height=400
        situacion.content_padding=ft.padding.only(bottom=10,top=3)
        no_complete= ft.Container(
            visible=False,
            width=300,
            alignment=ft.alignment.center,
            content=ft.Column(
                horizontal_alignment=ft.CrossAxisAlignment.CENTER,
                controls=[
                    ft.Text(
                        "DEBE COMPLETAR TODOS LOS CAMPOS",
                        color=ft.colors.YELLOW_ACCENT_700,
                        weight=ft.FontWeight.BOLD,
                    ),
                    ft.Divider(
                        height=9,
                        thickness=3,
                        color = ft.colors.YELLOW_ACCENT_700,
                    )
                ]
            )
        )
        editbox=ft.AlertDialog(
            modal=True,
            title=ft.Text(f"Ventana de Edicion",
                color=ft.colors.LIGHT_BLUE_900,
                weight=ft.FontWeight.BOLD,
                text_align=ft.TextAlign.CENTER
            ),
            bgcolor=ft.colors.WHITE,
            shadow_color=ft.colors.BLACK,
            shape=ft.RoundedRectangleBorder(radius=0),
            content=ft.Container(
                width=800,
                height=500,
                content=ft.Row(
                    
                    controls=[
                        ft.Column(
                            controls=[
                                nacionalidad,
                                cedula,
                                nombre,
                                edad,
                                ocupacion,
                                lugar,
                            ]
                        ),
                        ft.Column(
                            controls=[
                                estudios,
                                cargo,
                                vehiculo,
                                telefono,
                                estado_civil,
                                hijos,
                            ]
                        ),
                        ft.Column(
                            controls=[
                                responsabilidad,
                                situacion,
                            ]
                        ),
                    ]
                ),
            ),
            actions=[
                ft.Row(
                    alignment=ft.MainAxisAlignment.SPACE_BETWEEN,
                    controls=[
                        ft.ElevatedButton(
                            "Eliminar del Dashboard",
                            bgcolor=ft.colors.RED,
                            color=ft.colors.WHITE,
                            on_click=lambda e: delete_member(member.id_member),
                            style=ft.ButtonStyle(
                                shape=ft.RoundedRectangleBorder(radius=0)
                            ), 
                        ),
                        no_complete,
                        ft.Row(
                            controls=[
                                ft.ElevatedButton(
                                    "Desechar Cambios",
                                    bgcolor=ft.colors.ORANGE_ACCENT_700,
                                    color=ft.colors.WHITE,
                                    on_click=close_dlg,
                                    style=ft.ButtonStyle(
                                        shape=ft.RoundedRectangleBorder(radius=0)
                                    ), 
                                ),
                                ft.ElevatedButton(
                                    "Guardar",
                                    bgcolor=ft.colors.LIGHT_BLUE_900,
                                    color=ft.colors.WHITE,
                                    style=ft.ButtonStyle(
                                        shape=ft.RoundedRectangleBorder(radius=0)
                                    ), 
                                    on_click=lambda e: change_data(no_complete,Member(cedula.value,nombre.value,edad.value,telefono.value,ocupacion.value,lugar.value,estudios.value,vehiculo.value,responsabilidad.value,estado_civil.value,hijos.value,nacionalidad.value,cargo.value,situacion.value,member.id_member)),
                                ),
                            ]
                        )
                    ]
                )
                
            ],
            actions_alignment=ft.MainAxisAlignment.END,
        )
        return editbox
    
    def open_edit(e):
        # accede a el control data, y recibe el valor de esa variable a traves de e.control.data y abre el dialog
        member=e.control.data
        dialog=edit(e,member)
        page.dialog=dialog
        dialog.open=True
        page.update()
    
    def open_dlg(e,name,situation):
        # retorna el Alertdialog tomamdo como parametro name y situation
        alert=ft.AlertDialog(
            title=ft.Text(f"Información General de {name}",
                color=ft.colors.LIGHT_BLUE_900,
                weight=ft.FontWeight.BOLD
            ),
            bgcolor=ft.colors.WHITE,
            shadow_color=ft.colors.BLACK,
            shape=ft.RoundedRectangleBorder(radius=0),
            content=ft.Container(
                width=300,
                content=ft.Text(
                    value=situation,
                    color=ft.colors.BLACK,
                    text_align=ft.TextAlign.JUSTIFY
                ),
            ),
            actions_alignment=ft.MainAxisAlignment.END,
        )
        return alert
    
    def data(e):
        # accede a el control data, y recibe el valor de esa variable a traves de e.control.data y habre el dialog
        data=e.control.data
        name=data[0]
        situation=data[1]
        dialog=open_dlg(e,name,situation)
        page.dialog=dialog
        dialog.open=True
        page.update()
    
    def close_dlg(e):
        page.dialog.open=False
        page.update()
    #add icon y dialog
    def open_creator(e):
        nation=text_create(" Nacionalidad","",ft.icons.PERM_IDENTITY,15,ft.TextOnlyInputFilter())
        dni=text_create(" Cédula","",ft.icons.PERM_IDENTITY,10,ft.NumbersOnlyInputFilter())
        situation=text_create(" Situación","",ft.icons.LOCATION_HISTORY_SHARP,400,None)
        name=text_create(" Nombre Completo","",ft.icons.PERM_IDENTITY,55,ft.TextOnlyInputFilter())
        age=text_create(" Edad","",ft.icons.ACCESS_TIME_OUTLINED,2,ft.NumbersOnlyInputFilter())
        ocup=text_create(" Ocupación","",ft.icons.WORK,55,None)
        place=text_create(" Lugar de ocupación","",ft.icons.PLACE_ROUNDED,40,None)
        study=text_create(" Estudios","",ft.icons.HISTORY_EDU_SHARP,30,None)
        hierarchy=text_create(" Cargos","",ft.icons.WORKSPACE_PREMIUM,25,ft.TextOnlyInputFilter())
        respon=text_create(" Responsabilidad en la Iglesia","",ft.icons.FACT_CHECK_SHARP,35,None)
        vehicle=text_create(" Vehículo","",ft.icons.DIRECTIONS_CAR,20,ft.TextOnlyInputFilter())
        status=text_create(" Estado Civil","",ft.icons.FAMILY_RESTROOM_ROUNDED,15,ft.TextOnlyInputFilter())
        child=text_create(" Cantidad de Hijos","",ft.icons.CHILD_FRIENDLY_OUTLINED,1,ft.NumbersOnlyInputFilter())
        phone=text_create(" Teléfono","",ft.icons.PHONE_ROUNDED,15,ft.NumbersOnlyInputFilter())
        situation.multiline=True
        situation.width=880
        situation.height=160
        situation.content_padding=ft.padding.only(bottom=10,top=3)
        no_complete= ft.Container(
            visible=False,
            width=300,
            alignment=ft.alignment.center,
            content=ft.Column(
                horizontal_alignment=ft.CrossAxisAlignment.CENTER,
                controls=[
                    ft.Text(
                        "DEBE COMPLETAR TODOS LOS CAMPOS",
                        color=ft.colors.YELLOW_ACCENT_700,
                        weight=ft.FontWeight.BOLD,
                    ),
                    ft.Divider(
                        height=9,
                        thickness=3,
                        color = ft.colors.YELLOW_ACCENT_700,
                    )
                ]
            )
        )
        create_table= ft.AlertDialog(
            modal=True,
            title=ft.Text(f"Crear un Nuevo Registro",
                color=ft.colors.ORANGE_ACCENT_700,
                weight=ft.FontWeight.BOLD,
                text_align=ft.TextAlign.CENTER
            ),
            bgcolor=ft.colors.WHITE,
            shadow_color=ft.colors.BLACK,
            shape=ft.RoundedRectangleBorder(radius=0),
            content=ft.Container(
                width=1200,
                height=600,
            content=ft.Column(
                    controls=[
                        ft.Row(
                            alignment=ft.MainAxisAlignment.CENTER,
                            controls=[
                                no_complete,
                            ]
                        ),
                        ft.Row(
                            controls=[
                                ft.Column(
                                    controls=[
                                        nation,
                                        phone,
                                        status,
                                    ]
                                ),
                                ft.Column(
                                    controls=[
                                        dni,
                                        study,
                                        child,
                                    ]
                                ),
                                ft.Column(
                                    controls=[
                                        name,
                                        ocup,
                                        vehicle,
                                    ]
                                ),
                                ft.Column(
                                    controls=[
                                        age,
                                        place,
                                        hierarchy,
                                    ]
                                ),
                            ]
                        ),
                        ft.Row(
                            alignment=ft.MainAxisAlignment.CENTER,
                            controls=[
                                respon
                            ]
                        ),
                        ft.Row(
                            alignment=ft.MainAxisAlignment.CENTER,
                            controls=[
                                situation
                            ]
                        ),
                    ]
                ),
            ),
            actions=[
                ft.Row(
                    alignment=ft.MainAxisAlignment.SPACE_BETWEEN,
                    controls=[
                        ft.ElevatedButton(
                            "Desechar",
                            bgcolor=ft.colors.ORANGE_ACCENT_700,
                            color=ft.colors.WHITE,
                            on_click=close_dlg,
                            style=ft.ButtonStyle(
                                shape=ft.RoundedRectangleBorder(radius=0)
                            ), 
                        ),
                        ft.ElevatedButton(
                            "Guardar",
                            bgcolor=ft.colors.LIGHT_BLUE_900,
                            color=ft.colors.WHITE,
                            style=ft.ButtonStyle(
                                shape=ft.RoundedRectangleBorder(radius=0)
                            ), 
                            on_click=lambda e: save_create(no_complete,Member(dni.value,name.value,age.value,phone.value,ocup.value,place.value,study.value,vehicle.value,respon.value,status.value,child.value,nation.value,hierarchy.value,situation.value,None)),
                        ),
                    ]
                )
            ]
        )
        page.dialog=create_table
        create_table.open=True
        page.update()
    add.on_click=open_creator
    #tabla a retornar
    
    panel_list=ft.ExpansionPanelList(
        expand_icon_color=ft.colors.ORANGE_ACCENT_700,
        elevation=8,
        divider_color=ft.colors.LIGHT_BLUE_900,)
    columna=ft.Column(
        expand=True,
        scroll="auto",
        controls=[
            ft.Container(
                padding=ft.padding.only(10,10,15,10),
                content=panel_list
            )
        ]
    )
    #generacion de la pagina por primera vez
    for column in Member_list:
        member=Member(column[0],column[1],column[2],column[3],column[4],column[5],column[6],column[7],column[8],column[9],column[10],column[11],column[12],column[13],column[14])
        pnl=ft.ExpansionPanel(
            header=ft.Container(
                padding=ft.padding.all(15),
                content=ft.Row(
                    alignment=ft.MainAxisAlignment.SPACE_BETWEEN,
                    controls=[
                        ft.Container(
                            width=500,
                            content=ft.ListTile(
                                title=ft.Text(
                                    value=member.full_name,
                                    color=ft.colors.ORANGE_ACCENT_700,
                                    weight=ft.FontWeight.BOLD,
                                    size=18
                                ),
                                subtitle=ft.Text(
                                    value=member.occupation,
                                    color=ft.colors.LIGHT_BLUE_900,
                                    weight=ft.FontWeight.BOLD,
                                ),
                                leading=ft.IconButton(
                                    icon=ft.icons.INFO,
                                    data=[member.full_name,member.situation],
                                    icon_color=ft.colors.YELLOW_ACCENT_700,
                                    icon_size=30,
                                    on_click=data
                                ),
                            )
                        ),
                        ft.Container(
                            content=ft.Row(
                                controls=[
                                    ft.Text(
                                        value=member.hierarchy,
                                        color=ft.colors.LIGHT_BLUE_900,
                                        weight=ft.FontWeight.BOLD,
                                        size=16
                                    ),
                                    ft.IconButton(
                                        icon=ft.icons.EDIT,
                                        icon_color=ft.colors.ORANGE_ACCENT_700,
                                        data=member,
                                        on_click=open_edit)
                                ]
                            )
                        )
                    ]
                )
            ),
            bgcolor=ft.colors.WHITE,
            content=ft.Container(
                bgcolor=ft.colors.GREY_100,
                expand=True,
                height=250,
                padding=ft.padding.all(12),
                content=ft.Column(
                    scroll=ft.ScrollMode.AUTO,
                    controls=[
                        ft.Row(
                            expand=1,
                            alignment=ft.MainAxisAlignment.SPACE_AROUND,
                            vertical_alignment=ft.CrossAxisAlignment.START,
                            controls=[
                                ft.DataTable(
                                    expand=True,
                                    heading_row_color=ft.colors.LIGHT_BLUE_900,
                                    columns=[
                                        ft.DataColumn(ft.Text("Nacionalidad",color=ft.colors.WHITE),heading_row_alignment=ft.MainAxisAlignment.CENTER),
                                        ft.DataColumn(ft.Text('CI',color=ft.colors.WHITE),heading_row_alignment=ft.MainAxisAlignment.CENTER),
                                        ft.DataColumn(ft.Text('Edad',color=ft.colors.WHITE),heading_row_alignment=ft.MainAxisAlignment.CENTER),
                                        ft.DataColumn(ft.Text('Edo.Civil',color=ft.colors.WHITE),heading_row_alignment=ft.MainAxisAlignment.CENTER),
                                        ft.DataColumn(ft.Text('Hijos',color=ft.colors.WHITE),heading_row_alignment=ft.MainAxisAlignment.CENTER),
                                        
                                    ],
                                    rows=[
                                        ft.DataRow(
                                            cells=[
                                                ft.DataCell(
                                                    ft.Container(
                                                        margin=0,
                                                        expand=True,
                                                        alignment=ft.alignment.center,
                                                        content=ft.Text(
                                                            value=member.nationality,
                                                            color=ft.colors.BLACK,
                                                            weight=ft.FontWeight.BOLD,
                                                            text_align=ft.TextAlign.CENTER,
                                                            expand=True
                                                        )
                                                    ),
                                                ),
                                                ft.DataCell(
                                                    ft.Container(
                                                        margin=0,
                                                        expand=True,
                                                        alignment=ft.alignment.center,
                                                        content=ft.Text(
                                                            value=member.DNI,
                                                            color=ft.colors.BLACK,
                                                            weight=ft.FontWeight.BOLD,
                                                            text_align=ft.TextAlign.CENTER,
                                                            expand=True
                                                        )
                                                    ),
                                                ),
                                                ft.DataCell(
                                                    ft.Container(
                                                        margin=0,
                                                        expand=True,
                                                        alignment=ft.alignment.center,
                                                        content=ft.Text(
                                                            value=member.age,
                                                            color=ft.colors.BLACK,
                                                            weight=ft.FontWeight.BOLD,
                                                            text_align=ft.TextAlign.CENTER,
                                                            expand=True
                                                        )
                                                    ),
                                                ),
                                                ft.DataCell(
                                                    ft.Container(
                                                        margin=0,
                                                        expand=True,
                                                        alignment=ft.alignment.center,
                                                        content=ft.Text(value=member.civil_status,
                                                            color=ft.colors.BLACK,
                                                            weight=ft.FontWeight.BOLD,
                                                            text_align=ft.TextAlign.CENTER,
                                                            expand=True
                                                        )
                                                    ),
                                                ),
                                                ft.DataCell(
                                                    ft.Container(
                                                        margin=0,
                                                        expand=True,
                                                        alignment=ft.alignment.center,
                                                        content=ft.Text(value=member.childrens,
                                                            color=ft.colors.BLACK,
                                                            weight=ft.FontWeight.BOLD,
                                                            text_align=ft.TextAlign.CENTER,
                                                            expand=True
                                                        )
                                                    ),
                                                ),
                                            ]
                                        )
                                    ]
                                )
                            ]
                        ),
                        ft.Row(
                            expand=1,
                            alignment=ft.MainAxisAlignment.SPACE_AROUND,
                            vertical_alignment=ft.CrossAxisAlignment.START,
                            controls=[
                                ft.DataTable(
                                    expand=True,
                                    heading_row_color=ft.colors.ORANGE_ACCENT_700,
                                    columns=[
                                        ft.DataColumn(ft.Text("Estudios",color=ft.colors.WHITE),heading_row_alignment=ft.MainAxisAlignment.CENTER),
                                        ft.DataColumn(ft.Text("Lugar de Ocupación",color=ft.colors.WHITE),heading_row_alignment=ft.MainAxisAlignment.CENTER),
                                        ft.DataColumn(ft.Text("Responsabilidad",color=ft.colors.WHITE),heading_row_alignment=ft.MainAxisAlignment.CENTER),
                                        ft.DataColumn(ft.Text("Vehículo",color=ft.colors.WHITE),heading_row_alignment=ft.MainAxisAlignment.CENTER),
                                        ft.DataColumn(ft.Text("Teléfono",color=ft.colors.WHITE),heading_row_alignment=ft.MainAxisAlignment.CENTER),
                                    ],
                                    rows=[
                                        ft.DataRow(
                                            cells=[
                                                ft.DataCell(
                                                    ft.Container(
                                                        margin=0,
                                                        expand=True,
                                                        alignment=ft.alignment.center,
                                                        content=ft.Text(
                                                            value=member.knowledge,
                                                            color=ft.colors.BLACK,
                                                            weight=ft.FontWeight.BOLD,
                                                            text_align=ft.TextAlign.CENTER,
                                                            width=150,
                                                            expand=True
                                                        )
                                                    ),
                                                ),
                                                ft.DataCell(
                                                    ft.Container(
                                                        margin=0,
                                                        expand=True,
                                                        alignment=ft.alignment.center,
                                                        content=ft.Text(
                                                            value=member.occupation_place,
                                                            color=ft.colors.BLACK,
                                                            weight=ft.FontWeight.BOLD,
                                                            text_align=ft.TextAlign.CENTER,
                                                            expand=True,
                                                            width=150,
                                                        )
                                                    ),
                                                ),
                                                ft.DataCell(
                                                    ft.Container(
                                                        margin=0,
                                                        expand=True,
                                                        alignment=ft.alignment.center,
                                                        content=ft.Text(
                                                            member.responsabilities,
                                                            color=ft.colors.BLACK,
                                                            weight=ft.FontWeight.BOLD,
                                                            text_align=ft.TextAlign.CENTER,
                                                            width=150,
                                                            expand=True
                                                        )
                                                    ),
                                                ),
                                                ft.DataCell(
                                                    ft.Container(
                                                        margin=0,
                                                        expand=True,
                                                        alignment=ft.alignment.center,
                                                        content=ft.Text(
                                                            value=member.vehicle,
                                                            color=ft.colors.BLACK,
                                                            weight=ft.FontWeight.BOLD,
                                                            text_align=ft.TextAlign.CENTER,
                                                            width=150,
                                                            expand=True
                                                        )
                                                    ),
                                                ),
                                                ft.DataCell(
                                                    ft.Container(
                                                        margin=0,
                                                        expand=True,
                                                        alignment=ft.alignment.center,
                                                        content=ft.Text(
                                                            value=member.phone,
                                                            color=ft.colors.BLACK,
                                                            weight=ft.FontWeight.BOLD,
                                                            text_align=ft.TextAlign.CENTER,
                                                            expand=True,
                                                            width=150
                                                        )
                                                    ),
                                                ),
                                            ]
                                        )
                                    ]
                                )
                            ]
                        ),
                    ]
                )
            )
        )
        panel_list.controls.append(pnl)
        page.update()
    #Mostrar el panel segun la lista de miembros que se le pase
    def show_panel(iter):
        panel_list.controls.clear()
        for column in iter:
            member=Member(column[0],column[1],column[2],column[3],column[4],column[5],column[6],column[7],column[8],column[9],column[10],column[11],column[12],column[13],column[14])
            pnl=ft.ExpansionPanel(
                header=ft.Container(
                    padding=ft.padding.all(15),
                    content=ft.Row(
                        alignment=ft.MainAxisAlignment.SPACE_BETWEEN,
                        controls=[
                            ft.Container(
                                width=500,
                                content=ft.ListTile(
                                    title=ft.Text(
                                        value=member.full_name,
                                        color=ft.colors.ORANGE_ACCENT_700,
                                        weight=ft.FontWeight.BOLD,
                                        size=18
                                    ),
                                    subtitle=ft.Text(
                                        value=member.occupation,
                                        color=ft.colors.LIGHT_BLUE_900,
                                        weight=ft.FontWeight.BOLD,
                                    ),
                                    leading=ft.IconButton(
                                        icon=ft.icons.INFO,
                                        data=[member.full_name,member.situation],
                                        icon_color=ft.colors.YELLOW_ACCENT_700,
                                        icon_size=30,
                                        on_click=data
                                    ),
                                )
                            ),
                            ft.Container(
                                content=ft.Row(
                                    controls=[
                                        ft.Text(
                                            value=member.hierarchy,
                                            color=ft.colors.LIGHT_BLUE_900,
                                            weight=ft.FontWeight.BOLD,
                                            size=16
                                        ),
                                        ft.IconButton(
                                            icon=ft.icons.EDIT,
                                            icon_color=ft.colors.ORANGE_ACCENT_700,
                                            data=member,
                                            on_click=open_edit)
                                    ]
                                )
                            )
                        ]
                    )
                ),
                bgcolor=ft.colors.WHITE,
                content=ft.Container(
                    bgcolor=ft.colors.GREY_100,
                    expand=True,
                    height=250,
                    padding=ft.padding.all(12),
                    content=ft.Column(
                        scroll=ft.ScrollMode.AUTO,
                        controls=[
                            ft.Row(
                                expand=1,
                                alignment=ft.MainAxisAlignment.SPACE_AROUND,
                                vertical_alignment=ft.CrossAxisAlignment.START,
                                controls=[
                                    ft.DataTable(
                                        expand=True,
                                        heading_row_color=ft.colors.LIGHT_BLUE_900,
                                        columns=[
                                            ft.DataColumn(ft.Text("Nacionalidad",color=ft.colors.WHITE),heading_row_alignment=ft.MainAxisAlignment.CENTER),
                                            ft.DataColumn(ft.Text('CI',color=ft.colors.WHITE),heading_row_alignment=ft.MainAxisAlignment.CENTER),
                                            ft.DataColumn(ft.Text('Edad',color=ft.colors.WHITE),heading_row_alignment=ft.MainAxisAlignment.CENTER),
                                            ft.DataColumn(ft.Text('Edo.Civil',color=ft.colors.WHITE),heading_row_alignment=ft.MainAxisAlignment.CENTER),
                                            ft.DataColumn(ft.Text('Hijos',color=ft.colors.WHITE),heading_row_alignment=ft.MainAxisAlignment.CENTER),
                                            
                                        ],
                                        rows=[
                                            ft.DataRow(
                                                cells=[
                                                    ft.DataCell(
                                                        ft.Container(
                                                            margin=0,
                                                            expand=True,
                                                            alignment=ft.alignment.center,
                                                            content=ft.Text(
                                                                value=member.nationality,
                                                                color=ft.colors.BLACK,
                                                                weight=ft.FontWeight.BOLD,
                                                                text_align=ft.TextAlign.CENTER,
                                                                expand=True
                                                            )
                                                        ),
                                                    ),
                                                    ft.DataCell(
                                                        ft.Container(
                                                            margin=0,
                                                            expand=True,
                                                            alignment=ft.alignment.center,
                                                            content=ft.Text(
                                                                value=member.DNI,
                                                                color=ft.colors.BLACK,
                                                                weight=ft.FontWeight.BOLD,
                                                                text_align=ft.TextAlign.CENTER,
                                                                expand=True
                                                            )
                                                        ),
                                                    ),
                                                    ft.DataCell(
                                                        ft.Container(
                                                            margin=0,
                                                            expand=True,
                                                            alignment=ft.alignment.center,
                                                            content=ft.Text(
                                                                value=member.age,
                                                                color=ft.colors.BLACK,
                                                                weight=ft.FontWeight.BOLD,
                                                                text_align=ft.TextAlign.CENTER,
                                                                expand=True
                                                            )
                                                        ),
                                                    ),
                                                    ft.DataCell(
                                                        ft.Container(
                                                            margin=0,
                                                            expand=True,
                                                            alignment=ft.alignment.center,
                                                            content=ft.Text(value=member.civil_status,
                                                                color=ft.colors.BLACK,
                                                                weight=ft.FontWeight.BOLD,
                                                                text_align=ft.TextAlign.CENTER,
                                                                expand=True
                                                            )
                                                        ),
                                                    ),
                                                    ft.DataCell(
                                                        ft.Container(
                                                            margin=0,
                                                            expand=True,
                                                            alignment=ft.alignment.center,
                                                            content=ft.Text(value=member.childrens,
                                                                color=ft.colors.BLACK,
                                                                weight=ft.FontWeight.BOLD,
                                                                text_align=ft.TextAlign.CENTER,
                                                                expand=True
                                                            )
                                                        ),
                                                    ),
                                                ]
                                            )
                                        ]
                                    )
                                ]
                            ),
                            ft.Row(
                                expand=1,
                                alignment=ft.MainAxisAlignment.SPACE_AROUND,
                                vertical_alignment=ft.CrossAxisAlignment.START,
                                controls=[
                                    ft.DataTable(
                                        expand=True,
                                        heading_row_color=ft.colors.ORANGE_ACCENT_700,
                                        columns=[
                                            ft.DataColumn(ft.Text("Estudios",color=ft.colors.WHITE),heading_row_alignment=ft.MainAxisAlignment.CENTER),
                                            ft.DataColumn(ft.Text("Lugar de Ocupación",color=ft.colors.WHITE),heading_row_alignment=ft.MainAxisAlignment.CENTER),
                                            ft.DataColumn(ft.Text("Responsabilidad",color=ft.colors.WHITE),heading_row_alignment=ft.MainAxisAlignment.CENTER),
                                            ft.DataColumn(ft.Text("Vehículo",color=ft.colors.WHITE),heading_row_alignment=ft.MainAxisAlignment.CENTER),
                                            ft.DataColumn(ft.Text("Teléfono",color=ft.colors.WHITE),heading_row_alignment=ft.MainAxisAlignment.CENTER),
                                        ],
                                        rows=[
                                            ft.DataRow(
                                                cells=[
                                                    ft.DataCell(
                                                        ft.Container(
                                                            margin=0,
                                                            expand=True,
                                                            alignment=ft.alignment.center,
                                                            content=ft.Text(
                                                                value=member.knowledge,
                                                                color=ft.colors.BLACK,
                                                                weight=ft.FontWeight.BOLD,
                                                                text_align=ft.TextAlign.CENTER,
                                                                width=150,
                                                                expand=True
                                                            )
                                                        ),
                                                    ),
                                                    ft.DataCell(
                                                        ft.Container(
                                                            margin=0,
                                                            expand=True,
                                                            alignment=ft.alignment.center,
                                                            content=ft.Text(
                                                                value=member.occupation_place,
                                                                color=ft.colors.BLACK,
                                                                weight=ft.FontWeight.BOLD,
                                                                text_align=ft.TextAlign.CENTER,
                                                                expand=True,
                                                                width=150,
                                                            )
                                                        ),
                                                    ),
                                                    ft.DataCell(
                                                        ft.Container(
                                                            margin=0,
                                                            expand=True,
                                                            alignment=ft.alignment.center,
                                                            content=ft.Text(
                                                                member.responsabilities,
                                                                color=ft.colors.BLACK,
                                                                weight=ft.FontWeight.BOLD,
                                                                text_align=ft.TextAlign.CENTER,
                                                                width=150,
                                                                expand=True
                                                            )
                                                        ),
                                                    ),
                                                    ft.DataCell(
                                                        ft.Container(
                                                            margin=0,
                                                            expand=True,
                                                            alignment=ft.alignment.center,
                                                            content=ft.Text(
                                                                value=member.vehicle,
                                                                color=ft.colors.BLACK,
                                                                weight=ft.FontWeight.BOLD,
                                                                text_align=ft.TextAlign.CENTER,
                                                                width=150,
                                                                expand=True
                                                            )
                                                        ),
                                                    ),
                                                    ft.DataCell(
                                                        ft.Container(
                                                            margin=0,
                                                            expand=True,
                                                            alignment=ft.alignment.center,
                                                            content=ft.Text(
                                                                value=member.phone,
                                                                color=ft.colors.BLACK,
                                                                weight=ft.FontWeight.BOLD,
                                                                text_align=ft.TextAlign.CENTER,
                                                                expand=True,
                                                                width=150
                                                            )
                                                        ),
                                                    ),
                                                ]
                                            )
                                        ]
                                    )
                                ]
                            ),
                        ]
                    )
                )
            )
            panel_list.controls.append(pnl)
            page.update()
    #algoritmos de busqueda
    def serchinput(e):
        Member_list=ModelMember.dashboard()
        inp=search.value
        list_search=list(filter(lambda x:inp.lower() in x[1].lower() , Member_list))
        if inp !="":
            if len(list_search) > 0:
                show_panel(list_search)
                page.update()   
            else:
                panel_list.controls.clear()
                page.update()
        elif inp =="":
            panel_list.controls=None
            for column in Member_list:
                member=Member(column[0],column[1],column[2],column[3],column[4],column[5],column[6],column[7],column[8],column[9],column[10],column[11],column[12],column[13],column[14])
                pnl=ft.ExpansionPanel(
                        header=ft.Container(
                            padding=ft.padding.all(15),
                            content=ft.Row(
                                alignment=ft.MainAxisAlignment.SPACE_BETWEEN,
                                controls=[
                                    ft.Container(
                                        width=500,
                                        content=ft.ListTile(
                                            title=ft.Text(
                                                value=member.full_name,
                                                color=ft.colors.ORANGE_ACCENT_700,
                                                weight=ft.FontWeight.BOLD,
                                                size=18
                                            ),
                                            subtitle=ft.Text(
                                                value=member.occupation,
                                                color=ft.colors.LIGHT_BLUE_900,
                                                weight=ft.FontWeight.BOLD,
                                            ),
                                            leading=ft.IconButton(
                                                icon=ft.icons.INFO,
                                                data=[member.full_name,member.situation],
                                                icon_color=ft.colors.YELLOW_ACCENT_700,
                                                icon_size=30,
                                                on_click=data
                                            ),
                                        )
                                    ),
                                    ft.Container(
                                        content=ft.Row(
                                            controls=[
                                                ft.Text(
                                                    value=member.hierarchy,
                                                    color=ft.colors.LIGHT_BLUE_900,
                                                    weight=ft.FontWeight.BOLD,
                                                    size=16
                                                ),
                                                ft.IconButton(icon=ft.icons.EDIT,
                                                    icon_color=ft.colors.ORANGE_ACCENT_700,
                                                    data=member,
                                                    on_click=open_edit
                                                )
                                            ]
                                        )
                                    )
                                ]
                            )
                        ),
                        bgcolor=ft.colors.WHITE,
                        content=ft.Container(
                            bgcolor=ft.colors.GREY_100,
                            expand=True,
                            height=250,
                            padding=ft.padding.all(12),
                            content=ft.Column(
                                scroll=ft.ScrollMode.AUTO,
                                controls=[
                                    ft.Row(
                                        expand=1,
                                        alignment=ft.MainAxisAlignment.SPACE_AROUND,
                                        vertical_alignment=ft.CrossAxisAlignment.START,
                                        controls=[
                                            ft.DataTable(
                                                expand=True,
                                                heading_row_color=ft.colors.LIGHT_BLUE_900,
                                                columns=[
                                                    ft.DataColumn(ft.Text("Nacionalidad",color=ft.colors.WHITE),heading_row_alignment=ft.MainAxisAlignment.CENTER),
                                                    ft.DataColumn(ft.Text('CI',color=ft.colors.WHITE),heading_row_alignment=ft.MainAxisAlignment.CENTER),
                                                    ft.DataColumn(ft.Text('Edad',color=ft.colors.WHITE),heading_row_alignment=ft.MainAxisAlignment.CENTER),
                                                    ft.DataColumn(ft.Text('Edo.Civil',color=ft.colors.WHITE),heading_row_alignment=ft.MainAxisAlignment.CENTER),
                                                    ft.DataColumn(ft.Text('Hijos',color=ft.colors.WHITE),heading_row_alignment=ft.MainAxisAlignment.CENTER),
                                                    
                                                ],
                                                rows=[
                                                    ft.DataRow(
                                                        cells=[
                                                            ft.DataCell(
                                                                ft.Container(
                                                                    margin=0,
                                                                    expand=True,
                                                                    alignment=ft.alignment.center,
                                                                    content=ft.Text(
                                                                        value=member.nationality,
                                                                        color=ft.colors.BLACK,
                                                                        weight=ft.FontWeight.BOLD,
                                                                        text_align=ft.TextAlign.CENTER,
                                                                        expand=True
                                                                    )
                                                                ),
                                                            ),
                                                            ft.DataCell(
                                                                ft.Container(
                                                                    margin=0,
                                                                    expand=True,
                                                                    alignment=ft.alignment.center,
                                                                    content=ft.Text(
                                                                        value=member.DNI,
                                                                        color=ft.colors.BLACK,
                                                                        weight=ft.FontWeight.BOLD,
                                                                        text_align=ft.TextAlign.CENTER,
                                                                        expand=True
                                                                    )
                                                                ),
                                                            ),
                                                            ft.DataCell(
                                                                ft.Container(
                                                                    margin=0,
                                                                    expand=True,
                                                                    alignment=ft.alignment.center,
                                                                    content=ft.Text(
                                                                        value=member.age,
                                                                        color=ft.colors.BLACK,
                                                                        weight=ft.FontWeight.BOLD,
                                                                        text_align=ft.TextAlign.CENTER,
                                                                        expand=True
                                                                    )
                                                                ),
                                                            ),
                                                            ft.DataCell(
                                                                ft.Container(
                                                                    margin=0,
                                                                    expand=True,
                                                                    alignment=ft.alignment.center,
                                                                    content=ft.Text(value=member.civil_status,
                                                                        color=ft.colors.BLACK,
                                                                        weight=ft.FontWeight.BOLD,
                                                                        text_align=ft.TextAlign.CENTER,
                                                                        expand=True
                                                                    )
                                                                ),
                                                            ),
                                                            ft.DataCell(
                                                                ft.Container(
                                                                    margin=0,
                                                                    expand=True,
                                                                    alignment=ft.alignment.center,
                                                                    content=ft.Text(value=member.childrens,
                                                                        color=ft.colors.BLACK,
                                                                        weight=ft.FontWeight.BOLD,
                                                                        text_align=ft.TextAlign.CENTER,
                                                                        expand=True
                                                                    )
                                                                ),
                                                            ),
                                                        ]
                                                    )
                                                ]
                                            )
                                        ]
                                    ),
                                    ft.Row(
                                        expand=1,
                                        alignment=ft.MainAxisAlignment.SPACE_AROUND,
                                        vertical_alignment=ft.CrossAxisAlignment.START,
                                        controls=[
                                            ft.DataTable(
                                                expand=True,
                                                heading_row_color=ft.colors.ORANGE_ACCENT_700,
                                                columns=[
                                                    ft.DataColumn(ft.Text("Estudios",color=ft.colors.WHITE),heading_row_alignment=ft.MainAxisAlignment.CENTER),
                                                    ft.DataColumn(ft.Text("Lugar de Ocupacion",color=ft.colors.WHITE),heading_row_alignment=ft.MainAxisAlignment.CENTER),
                                                    ft.DataColumn(ft.Text("Responsabilidad",color=ft.colors.WHITE),heading_row_alignment=ft.MainAxisAlignment.CENTER),
                                                    ft.DataColumn(ft.Text("Vehiculo",color=ft.colors.WHITE),heading_row_alignment=ft.MainAxisAlignment.CENTER),
                                                    ft.DataColumn(ft.Text("Telefono",color=ft.colors.WHITE),heading_row_alignment=ft.MainAxisAlignment.CENTER),
                                                ],
                                                rows=[
                                                    ft.DataRow(
                                                        cells=[
                                                            ft.DataCell(
                                                                ft.Container(
                                                                    margin=0,
                                                                    expand=True,
                                                                    alignment=ft.alignment.center,
                                                                    content=ft.Text(
                                                                        value=member.knowledge,
                                                                        color=ft.colors.BLACK,
                                                                        weight=ft.FontWeight.BOLD,
                                                                        text_align=ft.TextAlign.CENTER,
                                                                        expand=True,
                                                                        width=150,
                                                                    )
                                                                ),
                                                            ),
                                                            ft.DataCell(
                                                                ft.Container(
                                                                    margin=0,
                                                                    expand=True,
                                                                    alignment=ft.alignment.center,
                                                                    content=ft.Text(
                                                                        value=member.occupation_place,
                                                                        color=ft.colors.BLACK,
                                                                        weight=ft.FontWeight.BOLD,
                                                                        text_align=ft.TextAlign.CENTER,
                                                                        expand=True,
                                                                        width=150,
                                                                    )
                                                                ),
                                                            ),
                                                            ft.DataCell(
                                                                ft.Container(
                                                                    margin=0,
                                                                    expand=True,
                                                                    alignment=ft.alignment.center,
                                                                    content=ft.Text(
                                                                        member.responsabilities,
                                                                        color=ft.colors.BLACK,
                                                                        weight=ft.FontWeight.BOLD,
                                                                        text_align=ft.TextAlign.CENTER,
                                                                        width=150,
                                                                        expand=True
                                                                    )
                                                                ),
                                                            ),
                                                            ft.DataCell(
                                                                ft.Container(
                                                                    margin=0,
                                                                    expand=True,
                                                                    alignment=ft.alignment.center,
                                                                    content=ft.Text(
                                                                        value=member.vehicle,
                                                                        color=ft.colors.BLACK,
                                                                        weight=ft.FontWeight.BOLD,
                                                                        text_align=ft.TextAlign.CENTER,
                                                                        width=150,
                                                                        expand=True
                                                                    )
                                                                ),
                                                            ),
                                                            ft.DataCell(
                                                                ft.Container(
                                                                    margin=0,
                                                                    expand=True,
                                                                    alignment=ft.alignment.center,
                                                                    content=ft.Text(
                                                                        value=member.phone,
                                                                        color=ft.colors.BLACK,
                                                                        weight=ft.FontWeight.BOLD,
                                                                        text_align=ft.TextAlign.CENTER,
                                                                        width=150,
                                                                        expand=True
                                                                    )
                                                                ),
                                                            ),
                                                        ]
                                                    )
                                                ]
                                            )
                                        ]
                                    ),
                                ]
                            )
                        )
                    )
                panel_list.controls.append(pnl)
            page.update()
    #on_change del buscador
    search.on_change= serchinput
    #Eliminar Registro
    def delete_member(id):
        ModelMember.delete_member(id)
        Member_list= ModelMember.dashboard()
        show_panel(Member_list)
        search.value=""
        page.dialog.open=False
        page.update()
    #guarda el edit y ejecuta otra vez el panel para actulizar la tabla
    def change_data(no_complete,member):
        if member.full_name and member.DNI and member.age and member.phone and member.occupation and member.occupation_place and member.knowledge and member.vehicle and member.responsabilities and member.civil_status and (member.childrens or member.childrens==0) and member.nationality and member.hierarchy and member.situation:
            ModelMember.edit_member(member)
            Member_list= ModelMember.dashboard()
            show_panel(Member_list)
            search.value=""
            page.dialog.open=False
            page.update()
        else:
            no_complete.visible=True
            no_complete.update()
            time.sleep(1.5)
            no_complete.visible= False
            no_complete.update()
    #guardar registro
    def save_create(no_complete,member):
        if member.full_name and member.DNI and member.age and member.phone and member.occupation and member.occupation_place and member.knowledge and member.vehicle and member.responsabilities and member.civil_status and member.nationality and member.hierarchy and member.situation:
            ModelMember.create_member(member)
            Member_list= ModelMember.dashboard()
            show_panel(Member_list)
            search.value=""
            page.dialog.open=False
            page.update()   
        else:
            no_complete.visible=True
            no_complete.update()
            time.sleep(1.5)
            no_complete.visible= False
            no_complete.update()
    return columna