import flet as ft
from components.general_table import panel
from components.event_table import event_panel
from components.asist_table import asist_panel
from components.config_table import config_panel

def sidebar(page,pres,topic,icon,nav):
    #Log-out
    def log_out(e):
        page.data={}
        page.go("/login")
    # dialog de info de la app
    def open_app_info(e):
        dialog= ft.AlertDialog(
            title=ft.Text(f"Información de la Aplicación",
                color=ft.colors.LIGHT_BLUE_900,
                weight=ft.FontWeight.BOLD,
                text_align=ft.TextAlign.CENTER
            ),
            bgcolor=ft.colors.WHITE,
            shadow_color=ft.colors.BLACK,
            shape=ft.RoundedRectangleBorder(radius=0),
            content=ft.Container(
                height=500,
                content=ft.Column(
                    controls=[
                        ft.Container(
                            alignment=ft.alignment.center,
                            content=ft.Image(
                                src="images/logo_tabernaculo.png",
                                width=175,
                                height=175,
                            ),
                        ),
                        ft.Container(
                            content=ft.ListTile(
                                title=ft.Text("TABERNÁCULO DB",
                                color=ft.colors.ORANGE_ACCENT_700,
                                weight=ft.FontWeight.BOLD,
                                text_align=ft.TextAlign.CENTER,
                                ),
                                subtitle=ft.Text(
                                    "Este sistema de base de datos fue realizado por Sebastián Alejandro Baptista Gómez, cedula de identidad V-30.222.622, con la ayuda de Cristian Javier Blanco Maldonado cedula de identidad V- 30.452.302, ambos estudiantes cursantes del 5to cuatrimestre de la carrera Informática, en el Instituto Universitario de Tecnología de Administración Industrial (IUTA). Dicha base de datos fue realizada en el lenguaje de programación Python (3.12.5), con la ayuda del framework FLET (0.24.1), junto a la librería Werkzeug (3.0.4), la base de datos se realizó en SQLite. El sistema fue realizado para la Iglesia Tabernáculo Del Dios Altísimo.",
                                    color=ft.colors.LIGHT_BLUE_900,
                                    weight=ft.FontWeight.BOLD,
                                    text_align=ft.TextAlign.CENTER,
                                    width=400,
                                )
                            ),
                        ),
                    ]
                ),
            )
        )
        page.dialog=dialog
        page.dialog.open=True
        page.update()
        return dialog
    #funciones para modificar los contenedores de self.topic y self.presentation de home.py
    def view_dashboard(e):
        topic.value="Dashboard"
        pres.controls=[panel(page,nav,icon)]
        icon.visible=True
        nav.visible=True
        nav.update()
        icon.update()
        pres.update()
        topic.update()
    
    def view_event(e):
        topic.value="Eventos"
        pres.controls=[event_panel(page,nav,icon)]
        icon.visible=True
        nav.visible=True
        nav.update()
        icon.update()
        pres.update()
        topic.update()
    
    def view_asist(e):
        topic.value="Asistencia del Servicio Dominical"
        pres.controls=[asist_panel(page,icon)]
        icon.visible=True
        nav.visible=False
        nav.update()
        icon.update()
        pres.update()
        topic.update()
    
    def view_config(e):
        topic.value="Configuración"
        pres.controls=[config_panel(page)]
        icon.visible=False
        nav.visible=False
        nav.update()
        icon.update()
        pres.update()
        topic.update()
    #endfuntions
    
    side=ft.Container(
        visible=True,
        margin=0,
        offset=ft.transform.Offset(0, 0),
        animate=ft.animation.Animation(500, ft.AnimationCurve.BOUNCE_OUT),
        width=230,
        bgcolor=ft.colors.WHITE,
        alignment=ft.alignment.center,
        content=ft.Column(
            spacing=0,
            horizontal_alignment=ft.CrossAxisAlignment.CENTER,
            alignment=ft.MainAxisAlignment.SPACE_BETWEEN,
            controls=[
                ft.Container(
                    margin=0,
                    expand=True,
                    content=ft.Column(
                        alignment=ft.MainAxisAlignment.CENTER,
                        controls=[
                            ft.Container(
                                bgcolor=ft.colors.ORANGE_ACCENT_700,
                                height=60,
                                padding=ft.padding.only(bottom=20,left=35,top=15),
                                content=ft.Row(
                                    controls=[
                                        ft.Text(
                                            "TABERNÁCULO DB",
                                            size=17,
                                            color=ft.colors.WHITE,
                                            weight=ft.FontWeight.BOLD,
                                        )
                                    ]
                                )
                            ),
                            ft.Row(
                                expand=True,
                                spacing=0,
                                controls=[   
                                    ft.Container(
                                        expand=True,
                                        content=ft.Column(
                                            alignment=ft.MainAxisAlignment.SPACE_BETWEEN,
                                            controls=[
                                                ft.Column(
                                                    spacing=20,
                                                    expand=True,
                                                    controls=[
                                                        ft.Container(
                                                            margin=ft.margin.only(left=15,right=15,top=5),
                                                            content=ft.ElevatedButton(
                                                                elevation=5,
                                                                style=ft.ButtonStyle(
                                                                    shape=ft.RoundedRectangleBorder(0),
                                                                    side=ft.BorderSide(2,color=ft.colors.ORANGE_ACCENT_700)
                                                                ),
                                                                bgcolor=ft.colors.WHITE,
                                                                on_click=view_dashboard,
                                                                content=ft.Container(
                                                                    clip_behavior=ft.ClipBehavior.ANTI_ALIAS,
                                                                    padding=ft.padding.only(top=10,left=5,bottom=10),
                                                                    content=ft.Row(
                                                                        controls=[
                                                                            ft.Icon(
                                                                                name=ft.icons.DASHBOARD_OUTLINED,color=ft.colors.ORANGE_ACCENT_700),
                                                                            ft.Text(
                                                                                "Dashboard",
                                                                                size=15,
                                                                                color=ft.colors.BLACK,
                                                                                weight=ft.FontWeight.BOLD,
                                                                            )
                                                                        ]
                                                                    )
                                                                )
                                                            ),
                                                        ),
                                                        ft.Container(
                                                            margin=ft.margin.only(left=15,right=15),
                                                            content=ft.ElevatedButton(
                                                                elevation=5,
                                                                style=ft.ButtonStyle(
                                                                    shape=ft.RoundedRectangleBorder(0),
                                                                    side=ft.BorderSide(2,color=ft.colors.ORANGE_ACCENT_700)
                                                                ),
                                                                bgcolor=ft.colors.WHITE,
                                                                on_click=view_event,
                                                                content=ft.Container(
                                                                    clip_behavior=ft.ClipBehavior.ANTI_ALIAS,
                                                                    padding=ft.padding.only(top=10,left=5,bottom=10),
                                                                    content=ft.Row(
                                                                        controls=[
                                                                            ft.Icon(
                                                                                name=ft.icons.EVENT_NOTE,color=ft.colors.ORANGE_ACCENT_700),
                                                                            ft.Text(
                                                                                "Eventos",
                                                                                size=15,
                                                                                color=ft.colors.BLACK,
                                                                                weight=ft.FontWeight.BOLD,
                                                                            )
                                                                        ]
                                                                    )
                                                                )
                                                            ),
                                                        ),
                                                        ft.Container(
                                                            margin=ft.margin.only(left=15,right=15),
                                                            content=ft.ElevatedButton(
                                                                elevation=5,
                                                                style=ft.ButtonStyle(
                                                                    shape=ft.RoundedRectangleBorder(0),
                                                                    side=ft.BorderSide(2,color=ft.colors.ORANGE_ACCENT_700)
                                                                ),
                                                                bgcolor=ft.colors.WHITE,
                                                                on_click=view_asist,
                                                                content=ft.Container(
                                                                    clip_behavior=ft.ClipBehavior.ANTI_ALIAS,
                                                                    padding=ft.padding.only(top=10,left=5,bottom=10),
                                                                    content=ft.Row(
                                                                        controls=[
                                                                            ft.Icon(
                                                                                name=ft.icons.APP_REGISTRATION_OUTLINED,color=ft.colors.ORANGE_ACCENT_700),
                                                                            ft.Text(
                                                                                "Asistencia",
                                                                                size=15,
                                                                                color=ft.colors.BLACK,
                                                                                weight=ft.FontWeight.BOLD,
                                                                            )
                                                                        ]
                                                                    )
                                                                )
                                                            ),
                                                        ),
                                                        ft.Container(
                                                            margin=ft.margin.only(left=15,right=15),
                                                            content=ft.ElevatedButton(
                                                                elevation=5,
                                                                style=ft.ButtonStyle(
                                                                    shape=ft.RoundedRectangleBorder(0),
                                                                    side=ft.BorderSide(2,color=ft.colors.ORANGE_ACCENT_700)
                                                                ),
                                                                bgcolor=ft.colors.WHITE,
                                                                on_click=view_config,
                                                                content=ft.Container(
                                                                    clip_behavior=ft.ClipBehavior.ANTI_ALIAS,
                                                                    padding=ft.padding.only(top=10,left=5,bottom=10),
                                                                    content=ft.Row(
                                                                        controls=[
                                                                            ft.Icon(
                                                                                name=ft.icons.MANAGE_ACCOUNTS,color=ft.colors.ORANGE_ACCENT_700),
                                                                            ft.Text(
                                                                                "Configuración",
                                                                                size=15,
                                                                                color=ft.colors.BLACK,
                                                                                weight=ft.FontWeight.BOLD,
                                                                            )
                                                                        ]
                                                                    )
                                                                )
                                                            ),
                                                        ),
                                                    ]
                                                ),
                                                ft.Column(
                                                    horizontal_alignment=ft.CrossAxisAlignment.START,
                                                    controls=[
                                                        ft.Container(
                                                            margin=ft.margin.only(left=10,right=10,bottom=20),
                                                            content=ft.ElevatedButton(
                                                                elevation=5,
                                                                style=ft.ButtonStyle(
                                                                    shape=ft.RoundedRectangleBorder(0),
                                                                    side=ft.BorderSide(2,color=ft.colors.LIGHT_BLUE_900)
                                                                ),
                                                                bgcolor=ft.colors.WHITE,
                                                                content=ft.Container(
                                                                    on_click= open_app_info,
                                                                    clip_behavior=ft.ClipBehavior.ANTI_ALIAS,
                                                                    padding=ft.padding.only(top=10,bottom=10),
                                                                    content=ft.Row(
                                                                        controls=[
                                                                            ft.Icon(
                                                                                name=ft.icons.APPS,color=ft.colors.LIGHT_BLUE_900),
                                                                            ft.Text(
                                                                                "Sobre la APP",
                                                                                size=15,
                                                                                color=ft.colors.BLACK,
                                                                                weight=ft.FontWeight.BOLD,
                                                                            )
                                                                        ]
                                                                    )
                                                                )
                                                            )
                                                        ),
                                                    ]
                                                ),
                                                ft.Column(
                                                    horizontal_alignment=ft.CrossAxisAlignment.START,
                                                    controls=[
                                                        ft.Container(
                                                            margin=ft.margin.only(left=10,right=10,bottom=20),
                                                            content=ft.ElevatedButton(
                                                                on_click=log_out,
                                                                elevation=5,
                                                                style=ft.ButtonStyle(
                                                                    shape=ft.RoundedRectangleBorder(0),
                                                                    side=ft.BorderSide(2,color=ft.colors.YELLOW_ACCENT_700)
                                                                ),
                                                                bgcolor=ft.colors.WHITE,
                                                                content=ft.Container(
                                                                    clip_behavior=ft.ClipBehavior.ANTI_ALIAS,
                                                                    padding=ft.padding.only(top=10,bottom=10),
                                                                    content=ft.Row(
                                                                        controls=[
                                                                            ft.Icon(
                                                                                name=ft.icons.LOGOUT,color=ft.colors.YELLOW_ACCENT_700),
                                                                            ft.Text(
                                                                                "Log-out",
                                                                                size=15,
                                                                                color=ft.colors.BLACK,
                                                                                weight=ft.FontWeight.BOLD,
                                                                            )
                                                                        ]
                                                                    )
                                                                )
                                                            )
                                                        ),
                                                    ]
                                                )
                                            ]
                                        ),
                                    ),
                                    ft.Container(
                                        padding=ft.padding.only(bottom=15),
                                        content=ft.VerticalDivider(
                                            color=ft.colors.BLACK,
                                            width=0.5,
                                            thickness=0.5
                                        ),
                                    )
                                ]
                            )
                        ]
                    )
                ),
            ]
        )
    )
    
    return side